openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
  description: API для управления заказами

servers:
  - url: http://localhost/api/v1

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Auth-Key

security:
  - ApiKeyAuth: []

paths:
  /orders/{order_id}:
    get:
      summary: Получить заказ по ID
      operationId: getOrderById
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: integer
          description: ID заказа
      responses:
        '200':
          description: Успешное получение заказа
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: integer
                    example: 1
                  items:
                    type: array
                    items:
                      type: integer
                      example: 1
                  done:
                    type: boolean
                    example: false

  /orders/{order_id}/items:
    post:
      summary: Добавить товары в заказ
      operationId: addItemsToOrder
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: integer
          description: ID заказа
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: integer
                    example: 1
              required:
                - items
      responses:
        '200':
          description: Успешное добавление товаров в заказ
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: integer
                    example: 1
                  items:
                    type: array
                    items:
                      type: integer
                      example: 1
                  done:
                    type: boolean
                    example: false


  /orders/{order_id}/done:
    post:
      summary: Пометить заказ как завершенный
      operationId: markOrderAsDone
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: integer
          description: ID заказа
      responses:
        '200':
          description: Успешное обновление заказа
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: integer
                    example: 1
                  done:
                    type: boolean
                    example: true

  /orders:
    get:
      summary: Получить список заказов
      operationId: getOrders
      parameters:
        - name: done
          in: query
          required: false
          schema:
            type: boolean
          description: Фильтр по завершенным заказам
      responses:
        '200':
          description: Успешное получение списка заказов
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    order_id:
                      type: integer
                      example: 1
                    done:
                      type: boolean
                      example: false

  /orders/store:
    post:  # Новый маршрут для создания заказа
      summary: Создать новый заказ
      operationId: storeOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: integer
                    example: 1
              required:
                - items
      responses:
        '201':
          description: Успешное создание заказа
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: integer
                    example: 1
                  items:
                    type: array
                    items:
                      type: integer
                      example: 1
                  done:
                    type: boolean
                    example: false
